name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Validate AWS Terraform
        run: |
          cd terraform/aws/environments/prod
          terraform init -backend=false
          terraform validate
      - name: Validate Azure Terraform
        run: |
          cd terraform/azure/environments/prod
          terraform init -backend=false
          terraform validate

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install flake8
      - run: flake8 app/src/ dr-scripts/ --max-line-length=120 --count --show-source --statistics

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install ansible-lint
      - run: ansible-lint ansible/ --exclude ansible/inventory/ || true

  docker-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/Dockerfile
          failure-threshold: warning
